import "./globals.css";

import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import { Providers } from "@/lib/providers";
import { Header } from "@/components/common/header";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={rubik.className}>
        <Providers>
          <Header />
          <main className="pt-12">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
